# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 136040113eef392f1f1d7836d51f17e75d72a9231d3749259e1f3e6bdfa3aae02f34bcecd0e2000317a16f37a5a64413867a6609d0b977adec8ad2952326c806

test:
  secret_key_base: c6a9e765aecb998a4a995b2139896193b142c3db6ca535b78fb0030dae9afff1d98fbc667fbc7fc703074b55574b5cd3a7bc6724a3a8274f98d43d245a4376f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
